///////////////////////////////////////////////////////////////////////////////
//
/// \file       price_tablegen.c
/// \brief      Probability price table generator
///
/// Compiling: gcc -std=c99 -o price_tablegen price_tablegen.c
///
//  Authors:    Igor Pavlov
//              Lasse Collin
//
//  This file has been put into the public domain.
//  You can do whatever you want with this file.
//
///////////////////////////////////////////////////////////////////////////////

#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include "range_encoder.h"


static uint32_t rc_prices[2][RC_PRICE_TABLE_SIZE];


static void
init_price_table(void)
{
	static const unsigned test_size = 0x4000;
	const unsigned test_div = test_size >> 8;
	uint8_t buf[0x3062];
	size_t pos;
	unsigned count[RC_PRICE_TABLE_SIZE];
	memset(rc_prices[0], 0, sizeof(rc_prices[0]));
	memset(rc_prices[1], 0, sizeof(rc_prices[1]));
	memset(count, 0, sizeof(count));
	for (probability i = 31; i <= RC_BIT_MODEL_TOTAL - 31; ++i) {
		lzma_range_encoder rc;
		rc_reset(&rc);
		pos = 0;
		for (unsigned j = 0; j < test_size; ++j) {
			probability prob = i;
			rc_bit(&rc, &prob, 0);
			rc_encode(&rc, buf, &pos, sizeof(buf));
		}
		rc_flush(&rc);
		rc_encode(&rc, buf, &pos, sizeof(buf));
		rc_prices[0][i >> RC_MOVE_REDUCING_BITS] += (unsigned)pos - 5;
		rc_reset(&rc);
		pos = 0;
		for (unsigned j = 0; j < test_size; ++j) {
			probability prob = i;
			rc_bit(&rc, &prob, 1);
			rc_encode(&rc, buf, &pos, sizeof(buf));
		}
		rc_flush(&rc);
		rc_encode(&rc, buf, &pos, sizeof(buf));
		rc_prices[1][i >> RC_MOVE_REDUCING_BITS] += (unsigned)pos - 5;
		++count[i >> RC_MOVE_REDUCING_BITS];
	}
	for (int i = 0; i < RC_PRICE_TABLE_SIZE; ++i) if (count[i]) {
		rc_prices[0][i] = (rc_prices[0][i] / count[i]) / test_div;
		rc_prices[1][i] = (rc_prices[1][i] / count[i]) / test_div;
	}

	return;
}


static void
print_price_table(void)
{
	printf("// This file has been automatically generated by price_tablegen.c.\n"
		"// The first and last elements of each table are never used.\n\n"
		"#include \"range_encoder.h\"\n\n"
		"const uint8_t lzma_rc_prices[2][RC_PRICE_TABLE_SIZE] = { {");

	const size_t array_size = sizeof(lzma_rc_prices[0])
			/ sizeof(lzma_rc_prices[0][0]);
	for (size_t bit = 0; bit < 2; ++bit) {
		for (size_t i = 0; i < array_size; ++i) {
			if (i % 8 == 0)
				printf("\n\t");

			printf("%4" PRIu32, rc_prices[bit][i]);

			if (i != array_size - 1)
				printf(",");
		}
		if (bit == 0)
			printf("\n}, {\n");
	}

	printf("\n} };\n");

	return;
}


int
main(void)
{
	init_price_table();
	print_price_table();
	return 0;
}
